# Generated by Django 4.2.1 on 2023-05-30 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='user_id',
            field=models.IntegerField(default=1),
        ),
    ]
