name: ci-backend-workflow
on: [push, pull_request]
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install --upgrade pip
      - run: pip install -r ./back/requirements.txt
      - run: python ./back/manage.py test
