name: ci-backend-workflow
on: [push, pull_request]
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: cd ./back
      - run: pip install --upgrade pip
      - run: pip install -r requirements.txt
      - run: python manage.py test
